site_name: OperationML
site_url: https://operationml.com/
extra:
  homepage: https://operationml.com/
  analytics:
    provider: google
    property: G-1TPGZD2FRV
nav:
  - Home: index.md
  - Guides:
    - guides/index.md
    - guides/how-to-upload-train-test-validation-datasets-with-dvc-into-s3-bucket.md
theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  language: en
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: orange
      accent: orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.top
plugins: []
